spring:
  config:
    import: application-auth.yml
    activate:
      on-profile: prod
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: back.ecommerce.config.jpa.CamelCaseToSnakeAndUpperCaseStrategy
    open-in-view: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
logging:
  discord:
    webhook-uri: ${DISCORD_WEBHOOK_URI}
  config: classpath:logback-spring.xml


cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    sqs:
      queue-name: email-queue
      url: ${AWS_SQS_URL}