spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: back.ecommerce.config.jpa.CamelCaseToSnakeAndUpperCaseStrategy
    show-sql: true
    open-in-view: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  config:
    import: application-auth.yml
logging:
  discord:
    webhook-uri: ${DISCORD_WEBHOOK_URI}
  config: classpath:logback-spring.xml
