spring:
  config:
    import: application-auth.yml
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: back.ecommerce.config.jpa.CamelCaseToSnakeAndUpperCaseStrategy
    open-in-view: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
logging:
  discord:
    webhook-uri: ${DISCORD_WEBHOOK_URI}
  config: classpath:logback-spring.xml
