spring:
  profiles:
    default: dev


---

spring:
  config:
    activate:
      on-profile: dev
    import: "classpath:application-dev.yml"

---

spring:
  config:
    activate:
      on-profile: prod
    import: "classpath:submodule/application-prod.yml"