spring:
  config:
    import: application-auth.yml
    activate:
      on-profile: prod
  redis:
    host: 13.209.41.22
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: back.ecommerce.config.jpa.CamelCaseToSnakeAndUpperCaseStrategy
    open-in-view: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ecommerce-db.csjv4hhcezsy.ap-northeast-2.rds.amazonaws.com:3306/ecommerce?useSSL=false&&allowPublicKeyRetrieval=true
    username: admin
    password: ss114545
logging:
  discord:
    webhook-uri: https://discord.com/api/webhooks/1149942255818375218/XStN3748RX9Dg5b5oAlNvfFkgLj0jFldqX46RS5Zzj66w-NDRMsO7EhArzZQrWMdCm9R
  config: classpath:logback-spring.xml

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIAY6NJZMGAB4CQQHN7
      secret-key: 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
    sqs:
      queue-name: email-queue
      url: https://sqs.ap-northeast-2.amazonaws.com/615073276288/email-queue
