name: CI with Gradle

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'main'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: set permission
        run: chmod +x ./gradlew

      - name: run test
        run: ./gradlew --info test


